In [1]:
import numpy as np

X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

In [2]:
def sigmoid(x):
    return 1.0 / (1.0 + np.exp(-x))

In [3]:
W = 2 * np.random.random((1, 3)) - 1
W

array([[ 0.24506194,  0.50141746, -0.991266  ]])

In [4]:
N = 4
for k in range(N):
    x = X[k, :].T
    v = np.matmul(W, x)
    y = sigmoid(v)

    print(y)

[0.27066209]
[0.37992925]
[0.32164898]
[0.43910711]


In [5]:
D = np.array([
    [0], [0], [1], [1]
])

In [6]:
def calc_output(W, x):
    v = np.matmul(W, x)
    y = sigmoid(v)

    return y

In [7]:
def calc_error(d, y):
    e = d - y
    delta = y * (1 - y) * e

    return delta

In [8]:
def delta_GD(W, X, D, alpha):
    for k in range(4):
        x = X[k, :].T
        d = D[k]

        y = calc_output(W, x)
        delta = calc_error(d, y)

        dW = alpha * delta * x
        W = W + dW
        
    return W

In [9]:
alpha = 0.9
for epoch in range(10000):
    W = delta_GD(W, X, D, alpha)
    print(W)

[[ 0.49877902  0.54595153 -0.86286312]]
[[ 0.73004718  0.55675852 -0.77599229]]
[[ 0.93213763  0.54132712 -0.73007647]]
[[ 1.1081021   0.51035772 -0.71512163]]
[[ 1.2632328   0.47166308 -0.72085033]]
[[ 1.40214992  0.43008191 -0.73943869]]
[[ 1.5282913   0.38845439 -0.76554526]]
[[ 1.64410478  0.34837108 -0.79571444]]
[[ 1.75133678  0.31065067 -0.82778751]]
[[ 1.85126324  0.27564213 -0.8604546 ]]
[[ 1.94484762  0.24341692 -0.89294455]]
[[ 2.03284311  0.21389052 -0.92482048]]
[[ 2.11585745  0.18689777 -0.95584918]]
[[ 2.19439408  0.16223814 -0.98591955]]
[[ 2.26887889  0.13970215 -1.01499249]]
[[ 2.33967796  0.11908585 -1.04307033]]
[[ 2.40710971  0.10019827 -1.07017848]]
[[ 2.47145374  0.08286467 -1.09635447]]
[[ 2.53295725  0.06692735 -1.1216414 ]]
[[ 2.59184008  0.05224518 -1.14608421]]
[[ 2.64829862  0.03869253 -1.16972748]]
[[ 2.70250903  0.02615781 -1.19261426]]
[[ 2.75462988  0.01454207 -1.21478546]]
[[ 2.80480433  0.00375752 -1.23627957]]
[[ 2.85316203 -0.00627373 -1.25713264]]


In [10]:
N = 4
for k in range(N):
    x = X[k, :].T
    v = np.matmul(W, x)
    y = sigmoid(v)

    print(y)


[0.01019354]
[0.00829571]
[0.99323978]
[0.99169029]


### XOR

In [11]:
X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

D = np.array([[0], [1], [1], [0]])

In [12]:
W = 2 * np.random.random((1, 3)) - 1
W

array([[ 0.09919739,  0.69031314, -0.2948225 ]])

In [13]:
alpha = 0.9

for epoch in range(10000):
    W = delta_GD(W, X, D, alpha)

In [14]:
N = 4
for k in range(N):
    x = X[k, :].T
    v = np.matmul(W, x)
    y = sigmoid(v)

    print(y)

[0.52965337]
[0.5]
[0.47034663]
[0.44090112]


In [15]:
def calc_output2(W1, W2, x):
    v1 = np.matmul(W1, x)
    y1 = sigmoid(v1)
    v = np.matmul(W2, y1)
    y = sigmoid(v)

    return y, y1

In [16]:
def calc_delta(d, y):
    e = d - y
    delta = y * (1 - y) * e

    return delta

In [17]:
def calc_delta1(W2, delta, y1):
    e1 = np.matmul(W2.T, delta)
    delta1 = y1 * (1- y1) * e1

    return delta1

In [27]:
def backprop_XOR(W1, W2, X, D, alpha):
    for k in range(4):
        x = X[k, :].T
        d = D[k]

        y, y1 = calc_output2(W1, W2, x)
        delta = calc_delta(d, y)
        delta1 = calc_delta1(W2, delta, y1)

        dW1 = (alpha*delta1).reshape(4,1) * x.reshape(1, 3)
        W1 = W1 + dW1

        dW2 = alpha * delta * y1
        W2 = W2 + dW2

        return W1, W2

In [28]:
X = np.array([
    [0, 0, 1],
    [0, 1, 1],
    [1, 0, 1],
    [1, 1, 1]
])

D = np.array([[0], [1], [1], [0]])

In [29]:
W1 = 2 * np.random.random((4, 3)) - 1
W2 = 2*np.random.random((1, 4)) - 1

In [30]:
alpha = 0.9
for epoch in range(10000):
    W1, W2 = backprop_XOR(W1, W2, X, D, alpha)

In [31]:
N = 4
for k in range(N):
    x = X[k, :].T
    v1 = np.matmul(W1, x)
    y1 = sigmoid(v1)

    v = np.matmul(W2, y1)
    y = sigmoid(v)

    print(y)


[0.00498802]
[0.01021193]
[0.00585661]
[0.0115031]
